export const FETCH_LIST_QUESTIONS_START = 'FETCH_LIST_QUESTIONS_START';
export const FETCH_LIST_QUESTIONS_SUCCESS = 'FETCH_LIST_QUESTIONS_SUCCESS';
export const FETCH_LIST_IMAGES_START = 'FETCH_LIST_IMAGES_START';
export const FETCH_LIST_IMAGES_SUCCESS = 'FETCH_LIST_IMAGES_SUCCESS';